# Generated by Django 5.1.6 on 2025-05-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
