# Generated by Django 5.1.6 on 2025-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0003_detectedstressor_stressors'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedstressor',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
